---

- name: Ensure DKIM path exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ anonaddy_uid }}"
    group: "{{ anonaddy_gid }}"
  with_items:
    - "{{ anonaddy_data_dir_path }}/dkim"

- name: Ensure DKIM private key is installed
  ansible.builtin.copy:
    content: "{{ anonaddy_dkim_signing_key }}"
    dest: "{{ anonaddy_data_dir_path }}/dkim/{{ anonaddy_domain }}.private"
    owner: "{{ anonaddy_uid }}"
    group: "{{ anonaddy_gid }}"
    mode: 0640