---

- block:
    - when: anonaddy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: anonaddy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

    - when: anonaddy_enabled | bool and anonaddy_dkim_signing_key != ''
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install_dkim.yml"
  tags:
    - setup-all
    - setup-anonaddy
    - install-all
    - install-anonaddy

- block:
    - when: anonaddy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/generate_dkim.yml"
  tags:
    - generate-anonaddy-dkim

- block:
    - when: anonaddy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/import_gpg.yml"
  tags:
    - import-anonaddy-gpg

- block:
    - when: anonaddy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/create_user.yml"
  tags:
    - create-anonaddy-user

- block:
    - when: not anonaddy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-anonaddy