---

- name: Fail if required AnonAddy settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - anonaddy_hostname
    - anonaddy_uid
    - anonaddy_gid
    - anonaddy_key
    - anonaddy_domain
    - anonaddy_secret
    - anonaddy_database_hostname
    - anonaddy_database_name
    - anonaddy_database_username
    - anonaddy_database_password
    
- when: anonaddy_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required AnonAddy Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - anonaddy_container_labels_traefik_hostname
        - anonaddy_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `anonaddy_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if anonaddy_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          anonaddy_container_labels_traefik_path_prefix (`{{ anonaddy_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/anonaddy`).
      when: "anonaddy_container_labels_traefik_path_prefix != '/' and anonaddy_container_labels_traefik_path_prefix[-1] == '/'"